# Generated by Django 5.2.4 on 2025-07-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rating_movie_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='rating',
            new_name='ratings',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='ratings',
        ),
    ]
