# Generated by Django 5.2.4 on 2025-07-19 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_rating_movie_ratings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='ratings',
            new_name='rating',
        ),
    ]
